# Generated by Django 3.0.1 on 2019-12-19 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('roll_type', models.CharField(choices=[('sub', 'SUB'), ('main', 'MAIN')], max_length=10)),
                ('body', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls_body', to='materials.Material')),
                ('gear_shaft', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls_gear', to='materials.Material')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls', to='projects.Project')),
                ('steam_shaft', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls_steam', to='materials.Material')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
