# Generated by Django 3.0.1 on 2019-12-22 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Not defined', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RollMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('material_number', models.CharField(max_length=50, unique=True)),
                ('finish_od', models.FloatField()),
                ('finish_len', models.FloatField()),
                ('inner_dia', models.FloatField()),
                ('inner_dia_margin', models.FloatField()),
                ('purchasing_od', models.FloatField()),
                ('purchasing_len', models.FloatField()),
                ('ic_depth', models.FloatField()),
                ('ic_hardness_min', models.IntegerField()),
                ('ic_hardness_max', models.IntegerField()),
                ('od_margin', models.FloatField()),
                ('qt_hardness_min', models.IntegerField()),
                ('qt_hardness_max', models.IntegerField()),
                ('substrate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Substrate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
