# Generated by Django 3.0.1 on 2019-12-23 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_rollmaterial_substrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Material Type',
            },
        ),
        migrations.AlterModelOptions(
            name='substrate',
            options={'verbose_name': 'Substrate'},
        ),
        migrations.RenameField(
            model_name='material',
            old_name='serial_no',
            new_name='serial',
        ),
        migrations.RenameField(
            model_name='rollmaterial',
            old_name='material_number',
            new_name='serial',
        ),
        migrations.RemoveField(
            model_name='material',
            name='drawing',
        ),
        migrations.RemoveField(
            model_name='material',
            name='inner_dia',
        ),
        migrations.RemoveField(
            model_name='material',
            name='length',
        ),
        migrations.RemoveField(
            model_name='material',
            name='outer_dia',
        ),
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default='Nonamed', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollmaterial',
            name='name',
            field=models.CharField(default='Nonamed', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rollmaterial',
            name='substrate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollmaterials', to='materials.Substrate'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='materials.MaterialType'),
        ),
    ]
