# Generated by Django 3.0.1 on 2019-12-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_auto_20191224_1700'),
        ('materials', '0003_auto_20191223_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rollmaterial',
            old_name='finish_len',
            new_name='outer_dia',
        ),
        migrations.RemoveField(
            model_name='rollmaterial',
            name='finish_od',
        ),
        migrations.RemoveField(
            model_name='rollmaterial',
            name='inner_dia_margin',
        ),
        migrations.RemoveField(
            model_name='rollmaterial',
            name='od_margin',
        ),
        migrations.RemoveField(
            model_name='rollmaterial',
            name='purchasing_len',
        ),
        migrations.RemoveField(
            model_name='rollmaterial',
            name='purchasing_od',
        ),
        migrations.AddField(
            model_name='rollmaterial',
            name='base_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='designs.PartsDesign'),
        ),
        migrations.AddField(
            model_name='rollmaterial',
            name='status',
            field=models.CharField(default='입고대기', max_length=150),
        ),
    ]
