# Generated by Django 3.0.1 on 2019-12-25 05:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20191224_1700'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_src00',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_src01',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_src02',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_src03',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_src04',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_vendor00',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_vendor01',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_vendor02',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_vendor03',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_vendor04',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_vendor05',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_vendor06',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_vendor07',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_vendor08',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='hardness_by_vendor09',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='heat_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='innder_dia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='is_acceptable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='issued_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 25, 5, 49, 49, 627161, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='material',
            field=models.ManyToManyField(related_name='inspection_reports', to='materials.RollMaterial'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='outer_dia_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='outer_dia_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='tag_photo',
            field=models.FileField(blank=True, null=True, upload_to='reports/inspection/'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='thickness_bottom_0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='thickness_bottom_180',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='thickness_bottom_270',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='thickness_bottom_90',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='thickness_upper_0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='thickness_upper_180',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='thickness_upper_270',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='thickness_upper_90',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DefectReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('issued_date', models.DateField(default=datetime.datetime(2019, 12, 25, 5, 49, 49, 627161, tzinfo=utc))),
                ('defect_type', models.CharField(choices=[('ic_crack', 'induction hardening crack'), ('deviation', 'spec deviation'), ('macro', 'macro streak flow'), ('overcutted', 'overcutted'), ('fault', 'manufacturing fault')], max_length=255)),
                ('description', models.TextField()),
                ('photo', models.FileField(upload_to='defect/photos/')),
                ('is_acceptable', models.BooleanField(default=False)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_reports', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_reports', to='materials.RollMaterial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
