# Generated by Django 3.0.1 on 2019-12-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsdesign',
            name='model_name',
            field=models.CharField(max_length=200),
        ),
    ]
