# Generated by Django 3.0.1 on 2019-12-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(max_length=150)),
                ('issued_date', models.DateField()),
                ('order_to', models.CharField(max_length=150)),
                ('order_from', models.CharField(default='SRC', max_length=150)),
                ('revision', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
